# common config
baseURL = 'https://tj-csccg.github.io/TJCS-F2F/'
copyright = 'TJ-CSCCG / Tongji Univ. CS(&IS) Curriculum Cooperation Group'
languageCode = 'zh-cn'
theme = 'hugo-ink'
title = 'TJCS-F2F'

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  avatar = 'https://avatars.githubusercontent.com/u/67193306'
  subtitle = 'Face to Face, Tongji University Computer Science(&Information Security)'
  enableGitalk = true
  busuanzi = true

[[params.social]]
  icon = 'github'
  name = 'Github'
  url = 'https://github.com/tj-csccg/TJCS-F2F'

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Nav.
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3
[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4